;; Test payload WASM module for benchmarking
;; Computes fibonacci(30) - deterministic, fixed iterations
(module
  (func $fibonacci (param $n i32) (result i32)
    (if (i32.lt_s (local.get $n) (i32.const 2))
      (return (local.get $n))
    )
    (if (i32.eq (local.get $n) (i32.const 2))
      (return (i32.const 1))
    )
    (if (i32.eq (local.get $n) (i32.const 3))
      (return (i32.const 2))
    )
    (call $fibonacci (i32.sub (local.get $n) (i32.const 1)))
    (call $fibonacci (i32.sub (local.get $n) (i32.const 2)))
    (i32.add)
  )
  
  (func (export "_start")
    ;; Run fibonacci 10 times
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
    (call $fibonacci (i32.const 30))
    (drop)
  )
)