//! Recovery policy — typed, failure-mode-keyed advice.
//!
//! Replaces the prior `generate_recovery_suggestions()` which returned the
//! same two strings for every failure mode (both AI scorers flagged this
//! as the #1 systemic defect at 26% mean accuracy). The new design has
//! three layers:
//!
//!   * `RecoveryAction` — a structured suggestion with provenance, so the
//!     analyzer can tell whether advice came from the static policy, an
//!     instinct store (Phase B), or an LLM (Phase B).
//!   * `RecoveryPolicy` — a trait the hypervisor consults. Phase A ships
//!     `StaticPolicy`, which already returns *different* advice per
//!     `FailureMode`. Phase B adds `InstinctPolicy` and `LLMPolicy` as
//!     additional layers.
//!   * `LayeredPolicy` — combines policies in priority order and de-dupes.
//!
//! `StaticPolicy` is intentionally exhaustive over `FailureMode` so adding
//! a new variant is a compile error until the policy is updated.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::failure_mode::FailureMode;

/// Where a recovery action originated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecoverySource {
    /// Hard-coded mapping in `StaticPolicy`. Always available.
    Static,
    /// Learned from past failures (Phase B: continuous-learning-v2 port).
    Instinct,
    /// Generated by an LLM consulted at recovery time (Phase B, optional).
    Llm,
}

/// One structured recovery suggestion.
///
/// `confidence` ∈ [0.0, 1.0] — `StaticPolicy` emits 1.0 for primary advice
/// and 0.6 for less specific suggestions. `non_retryable` is `true` for
/// deterministic failure modes where retrying with the same inputs is
/// guaranteed to fail again.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAction {
    pub description: String,
    pub confidence: f32,
    pub source: RecoverySource,
    pub non_retryable: bool,
    /// Set when this action came from the instinct store. Used by the
    /// outcome-feedback loop in `NexusHypervisor::execute_with_retry` to
    /// credit (or debit) the instinct based on the next attempt's result.
    #[serde(default)]
    pub instinct_id: Option<Uuid>,
}

impl RecoveryAction {
    pub fn new(description: impl Into<String>, source: RecoverySource) -> Self {
        RecoveryAction {
            description: description.into(),
            confidence: 1.0,
            source,
            non_retryable: false,
            instinct_id: None,
        }
    }

    pub fn with_confidence(mut self, c: f32) -> Self {
        self.confidence = c.clamp(0.0, 1.0);
        self
    }

    pub fn with_non_retryable(mut self, nr: bool) -> Self {
        self.non_retryable = nr;
        self
    }

    pub fn with_instinct_id(mut self, id: Uuid) -> Self {
        self.instinct_id = Some(id);
        self
    }
}

/// Pluggable recovery-action generator. Implementations must be pure
/// (no side effects from `recover()`); persistence belongs to the
/// instinct store called separately.
pub trait RecoveryPolicy: Send + Sync {
    fn recover(&self, mode: &FailureMode, operation: &str) -> Vec<RecoveryAction>;
}

/// Phase A: hard-coded, failure-mode-keyed static policy.
///
/// Every `FailureMode` variant gets a tailored response. The match is
/// exhaustive so adding a new variant is a compile error until the policy
/// is updated.
pub struct StaticPolicy;

impl StaticPolicy {
    pub fn new() -> Self {
        StaticPolicy
    }
}

impl Default for StaticPolicy {
    fn default() -> Self {
        Self::new()
    }
}

impl RecoveryPolicy for StaticPolicy {
    fn recover(&self, mode: &FailureMode, _operation: &str) -> Vec<RecoveryAction> {
        let mk = |s: &str| RecoveryAction::new(s, RecoverySource::Static);
        match mode {
            FailureMode::Timeout { limit_ms, .. } => vec![
                mk(&format!(
                    "Watchdog fired at {limit_ms} ms; the sandbox guard already contained the run."
                )),
                mk("Add a per-tool fuel cap or iteration bound; convert any unbounded loop to a bounded/streaming algorithm with cooperative yield points.")
                    .with_confidence(0.9),
                mk("Only raise the timeout / fuel budget if profiling shows progress is being made.")
                    .with_confidence(0.7),
            ],
            FailureMode::FuelExhausted { limit } => vec![
                mk(&format!(
                    "Fuel budget of {limit} instructions was consumed; the guard worked as designed."
                )),
                mk("Profile the WASM to find the hot loop, then either reduce its iteration count or raise the per-tool fuel cap with an explicit business rationale.")
                    .with_confidence(0.9),
                mk("Consider iterative or memoized algorithms instead of naive recursion/iteration over large inputs.")
                    .with_confidence(0.7),
            ],
            FailureMode::TrapUnreachable => vec![
                mk("Deterministic `unreachable` instruction reached — likely an assertion failure or unhandled enum arm in the guest module.")
                    .with_non_retryable(true),
                mk("Locate the failing instruction via the wasm backtrace (function index + offset). Fix the guest code or the invariant it expected.")
                    .with_confidence(0.9)
                    .with_non_retryable(true),
                mk("Do NOT auto-retry with identical inputs; this failure is deterministic.")
                    .with_confidence(1.0)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapDivByZero => vec![
                mk("Integer divide-by-zero — guard the divisor (`if denom == 0 { return … }`) or use checked-division at the call site.")
                    .with_non_retryable(true),
                mk("Audit the input contract that allowed a zero divisor through; validation at the boundary is the right fix.")
                    .with_confidence(0.9)
                    .with_non_retryable(true),
                mk("Do NOT auto-retry with identical inputs; this failure is deterministic.")
                    .with_confidence(1.0)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapIntegerOverflow => vec![
                mk("Integer overflow trap — switch to wrapping/saturating arithmetic at the offending op, or widen the type.")
                    .with_non_retryable(true),
                mk("Add a range check at the input boundary so out-of-range values are rejected before they reach the arithmetic.")
                    .with_confidence(0.85)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapBadConversionToInteger => vec![
                mk("Float-to-int conversion produced an out-of-range or NaN value; use a saturating-conversion variant or clamp the input.")
                    .with_non_retryable(true),
                mk("If the source float is NaN, treat that case explicitly instead of converting.")
                    .with_confidence(0.85)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapStackOverflow => vec![
                mk("Call stack exhausted — convert the recursive function to iteration, add an explicit depth bound, or restructure into trampolines.")
                    .with_non_retryable(true),
                mk("Reject modules with unbounded recursion at validation; only legitimately deep, bounded workloads should raise the stack limit.")
                    .with_confidence(0.85)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapMemoryOutOfBounds => vec![
                mk("Out-of-bounds linear-memory access — bounds-check the index before the load/store or use a memory.size guard.")
                    .with_non_retryable(true),
                mk("Inspect the guest allocator for an off-by-one; ensure memory.grow happens before any access beyond the original heap.")
                    .with_confidence(0.85)
                    .with_non_retryable(true),
            ],
            FailureMode::TrapHeapMisaligned => vec![
                mk("Atomic operation on a non-shared / misaligned address — ensure the memory is shared and the address is naturally aligned for the atomic width.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapTableOutOfBounds => vec![
                mk("Out-of-bounds table access — check the index against `table.size` before `call_indirect`.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapIndirectCallToNull => vec![
                mk("Indirect call to a null table slot — populate the table entry with `table.set` before the call, or guard the slot at the call site.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapBadSignature => vec![
                mk("Indirect-call signature mismatch — make the callee's actual signature match the `call_indirect` signature.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapNullReference => vec![
                mk("Null reference dereferenced — null-check before use, or initialize the ref before passing it to the trapping op.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapCastFailure => vec![
                mk("Reference cast failed — guard with `ref.test` before `ref.cast`, or fix the upstream type.")
                    .with_non_retryable(true),
            ],
            FailureMode::TrapOther(detail) => vec![
                mk(&format!(
                    "Deterministic WASM trap (subtype not yet classified): {detail}. Treat as non-retryable; classify the subtype before deciding on remediation."
                ))
                    .with_non_retryable(true),
            ],
            FailureMode::MemoryLimitExceeded { pages, limit_pages } => vec![
                mk(&format!(
                    "WASM memory grew to {pages} pages but the per-tool limit is {limit_pages}; raise `max_memory_pages` or fix the guest allocator."
                )),
                mk("Stream large inputs rather than buffering them in linear memory; release no-longer-needed regions.")
                    .with_confidence(0.85),
            ],
            FailureMode::InvalidModule(detail) => vec![
                mk(&format!(
                    "Module failed to load: {detail}. Re-validate the WASM bytes and the toolchain output before retrying."
                ))
                    .with_non_retryable(true),
                mk("Do NOT roll back; no execution occurred and no state was mutated.")
                    .with_confidence(1.0)
                    .with_non_retryable(true),
            ],
            FailureMode::MissingEntrypoint { expected } => vec![
                mk(&format!(
                    "Module exports no `{expected}` (or fallback `main`) function. Verify entrypoint at build time, or configure the executor to call the correct export explicitly."
                ))
                    .with_non_retryable(true),
                mk("Do NOT roll back; nothing executed.")
                    .with_confidence(1.0)
                    .with_non_retryable(true),
            ],
            FailureMode::HostError(detail) => vec![
                mk(&format!(
                    "Host-side error during execution plumbing: {detail}. This indicates a Nexus bug or a configuration issue, not a guest problem; capture full logs and file an issue."
                )),
            ],
        }
    }
}

/// Combine N policies in priority order and de-dupe by description.
pub struct LayeredPolicy {
    layers: Vec<Box<dyn RecoveryPolicy>>,
}

impl LayeredPolicy {
    pub fn new(layers: Vec<Box<dyn RecoveryPolicy>>) -> Self {
        LayeredPolicy { layers }
    }
}

impl RecoveryPolicy for LayeredPolicy {
    fn recover(&self, mode: &FailureMode, operation: &str) -> Vec<RecoveryAction> {
        let mut out: Vec<RecoveryAction> = Vec::new();
        let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
        for layer in &self.layers {
            for action in layer.recover(mode, operation) {
                if seen.insert(action.description.clone()) {
                    out.push(action);
                }
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn modes() -> Vec<FailureMode> {
        vec![
            FailureMode::Timeout { limit_ms: 500, observed_ms: 502 },
            FailureMode::FuelExhausted { limit: 10_000_000 },
            FailureMode::TrapUnreachable,
            FailureMode::TrapDivByZero,
            FailureMode::TrapIntegerOverflow,
            FailureMode::TrapBadConversionToInteger,
            FailureMode::TrapStackOverflow,
            FailureMode::TrapMemoryOutOfBounds,
            FailureMode::TrapHeapMisaligned,
            FailureMode::TrapTableOutOfBounds,
            FailureMode::TrapIndirectCallToNull,
            FailureMode::TrapBadSignature,
            FailureMode::TrapNullReference,
            FailureMode::TrapCastFailure,
            FailureMode::TrapOther("Interrupt".into()),
            FailureMode::MemoryLimitExceeded { pages: 100, limit_pages: 1 },
            FailureMode::InvalidModule("bad header".into()),
            FailureMode::MissingEntrypoint { expected: "_start".into() },
            FailureMode::HostError("snapshot create failed".into()),
        ]
    }

    #[test]
    fn static_policy_emits_action_for_every_variant() {
        let policy = StaticPolicy::new();
        for mode in modes() {
            let actions = policy.recover(&mode, "op");
            assert!(
                !actions.is_empty(),
                "no actions emitted for {:?}",
                mode
            );
        }
    }

    #[test]
    fn static_policy_emits_distinct_first_actions_per_variant() {
        // The validation defect was that every variant produced the SAME
        // two strings. Assert every variant's first action is distinct.
        let policy = StaticPolicy::new();
        let mut first_actions: std::collections::HashSet<String> =
            std::collections::HashSet::new();
        for mode in modes() {
            let actions = policy.recover(&mode, "op");
            let first = actions[0].description.clone();
            assert!(
                first_actions.insert(first.clone()),
                "duplicate first-action `{}` (mode {:?})",
                first,
                mode
            );
        }
    }

    #[test]
    fn deterministic_modes_marked_non_retryable() {
        let policy = StaticPolicy::new();
        let deterministic = [
            FailureMode::TrapDivByZero,
            FailureMode::TrapUnreachable,
            FailureMode::MissingEntrypoint { expected: "_start".into() },
            FailureMode::InvalidModule("x".into()),
        ];
        for mode in deterministic {
            let actions = policy.recover(&mode, "op");
            assert!(
                actions.iter().any(|a| a.non_retryable),
                "no non_retryable action emitted for deterministic {:?}",
                mode
            );
        }
    }

    #[test]
    fn layered_policy_dedupes_descriptions() {
        struct DupPolicy;
        impl RecoveryPolicy for DupPolicy {
            fn recover(&self, _m: &FailureMode, _o: &str) -> Vec<RecoveryAction> {
                vec![RecoveryAction::new("same", RecoverySource::Instinct)]
            }
        }
        let p = LayeredPolicy::new(vec![Box::new(DupPolicy), Box::new(DupPolicy)]);
        let actions = p.recover(&FailureMode::TrapUnreachable, "op");
        assert_eq!(actions.len(), 1);
    }
}
